### ISSUE TITLE
correggere modalità di immissione dati

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#1]
La modalità attuale di immissione dei dati è molto scomoda.
Attualmente per fare una prova occorre digitare troppe informazioni distinte e troppo lunghe.
Modificate il programma perchè la posizine venga fornita in un passo solo (per es: *a3* invece che chiedere separatamente *a* e *3*). Inoltre fare in modo che l'utente possa usare maiuscole o minuscole indifferentemente.
Anche per l'orientamento non chiedete che si tebba digitare l'intera parola *orizzontale* o *verticale*, ma anche solo una lettere *o* oppure *v* (ovviamente anche in questo caso indifferentemente minuscola o maiuscola).

**Comment by Frise99** [comment]
Sono state apportate alcune modifiche al codice per semplificare l'inserimento delle coordinate e dell'orientamento delle navi, così come la scelta della quantità di ogni tipo di nave. Le modifiche consentono una maggiore flessibilità e rendono il processo più user-friendly.

Per quanto riguarda l'inserimento delle coordinate, è ora possibile inserire entrambe le coordinate (colonna e riga) in un unico input. Ad esempio, invece di inserire la colonna e la riga separatamente, come "A" e "1", è possibile inserire direttamente "A1" indifferentemente da lettere maiuscole o minuscole. Questa modifica semplifica l'input per gli utenti.

Per l'inserimento dell'orientamento della nave, è stato semplificato l'utilizzo delle lettere. Ora è sufficiente inserire la lettera "o" per indicare un'orientazione orizzontale e la lettera "v" per indicare un'orientazione verticale. Inoltre, non importa se le lettere sono maiuscole o minuscole, poiché entrambe vengono considerate valide.

Per quanto riguarda la scelta della quantità di ogni tipo di nave, è possibile specificare direttamente il nome della nave seguito dal numero desiderato. Ad esempio, se si desidera impostare 3 navi del tipo "Sottomarino", è sufficiente inserire "--sottomarino 3" e le altre navi saranno impostate tutte a 1 come di default senza la necessità di specificarle.

**Comment by Frise99** [comment]
Tutte le modifiche apportate si trovano nel branch _correzioni_
