### ISSUE TITLE
Effettuare un merge con il branch main

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#11]
Non lasciate la versione finale su un branch secondario. 
Effettuate un merge sul main riusolvendo eventuali conflitti (non ce ne dovrebbero essere se non avete fatto modifiche siul branch main da quando vi siete separati sul secondario) a favore del branch `correzzioni-2.0` (l'avete scritto con 2 'z', credo per un'errore di battitura, ma ormai si chiama così).

**Comment by salvatoredacri** [comment]
é stato effettuato il merge da `correzioni-2.0` sul main branch.
