### ISSUE TITLE
Vincolo di non adiacenza tra navi

### ISSUE THREAD

**Issue by supix** [salvatoredacri/Battaglia-Navale#13]
Il controllo del vincolo non funziona come dovrebbe. Sono riuscito a generare il seguente campo da gioco.

```
A B C D E F G H I
1 1 1 1 1 1 0 0 0 0
2 0 1 0 0 0 0 0 0 0
3 0 1 0 0 0 0 0 0 0
4 0 1 0 0 0 0 0 0 0
5 0 1 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0
9 0 0 0 0 0 0 0 0 0
```
Inoltre il controllo mi sembra contenga molto codice duplicato per i due casi orizzontale e verticale. Non sarebbe stato più facile creare un rettangolo _attorno_ alla nuova nave da posizionare e verificare che non vi fosse alcuna casella già occupata in questo rettangolo?

**Comment by Frise99** [comment]
Abbiamo rivisto la nostra funzione e ci siamo resi conto che nel codice originale era presente un piccolo errore che influenzava la correttezza dei controlli. Dopo un'attenta analisi, abbiamo apportato le modifiche necessarie per correggere l'errore e ora la funzione funziona correttamente come previsto.

Inoltre, abbiamo considerato l'opzione di utilizzare un'alternativa basata sulla creazione di un rettangolo attorno alla nuova nave da posizionare.  Sebbene questa soluzione sia valida, abbiamo scelto di mantenere la nostra implementazione originale corretta, poiché ci risulta più semplice e leggibile.

Tuttavia, abbiamo deciso di includere l'implementazione alternativa basata sulla creazione di un rettangolo come codice commentato all'interno del modulo `griglia`, in modo che sia visibile come opzione alternativa per ulteriori sviluppi o personalizzazioni future. Siamo consapevoli che ogni soluzione ha i suoi vantaggi e svantaggi, e abbiamo fatto questa scelta per mantenere la coerenza e la manutenibilità del codice.

Tutte le modifiche possono essere controllate nel branch 'Correzioni 2.0'

**Comment by supix** [comment]
Ho inviato una [pull request](https://github.com/salvatoredacri/Battaglia-Navale/pull/17) con una proposta di verifica della collisione tra navi. Leggete il commento della pull request per capire meglio cosa è stato fatto e cosa resta da fare.

Consideratela come una proposta di miglioramento del codice esistente. Valutate se è effettivamente migliorativa e decidete di conseguenza se e come incorporarla nel vostro codice.
