### ISSUE TITLE
Orientamento di un cacciatorpediniere

### ISSUE THREAD

**Issue by supix** [salvatoredacri/Battaglia-Navale#14]
https://github.com/salvatoredacri/Battaglia-Navale/blob/79ace74e7dedff3004ed9385cc717b538d1b8e83/giocatore.py#L64

Per un cacciatorpediniere l'orientamento non ha alcun senso.

**Comment by Frise99** [comment]
E' stata inserita all'interno della funzione '_posiziona_navi_' nel modulo `giocatore` una condizione affinché per un cacciatorpediniere non venga richiesto alcun orientamento poiché privo di  significato:

https://github.com/salvatoredacri/Battaglia-Navale/blob/17c2f7942351858a70f43dbfb8c333258e84d2ba/giocatore.py#L64

Tutte le modifiche possono essere controllate nel branch 'Correzioni 2.0'

**Comment by iannellog** [comment]
Il codice così modificato contiene un errore che non si manifesta, ma che va corretto.
Nel caso della nave di lunghezza 1 la variabile `orientamento` non viene *definita* (cioè non gli viene assegnato alcun valore). Alla riga 67 tale variabile viene però *usata*. Il programma non va in errore perché la nave di lunghezza 1 è l'ultma ad essere posizionata e pertanto la variabile `orientamento` è già stata creata (e contiene il valore assegnato alla nave precedente), ma se si cominciassa dalla nave di lunghezza 1 il programma andrebbe in errore perché la variabile `orientamento` non essendo mai stata *definita* in precedenza non esisterebbe.
Per correggere questo errore, l'**if** della riga 64 deve prevedere anche la clausola **else** che assegna alla variabile `orientamento` un valore di default (è indifferente quale).

**Comment by Frise99** [comment]
L'errore è stato corretto attraverso la soluzione suggerita. E' stata inserita la clausola else di modo che la nave di lunghezza 1 sia correttamente definita.
https://github.com/salvatoredacri/Battaglia-Navale/blob/f5c8c480ddbf6e801f42d288431e1c96d0ea9657/giocatore.py#L69
https://github.com/salvatoredacri/Battaglia-Navale/blob/f5c8c480ddbf6e801f42d288431e1c96d0ea9657/giocatore.py#L70
Tutte le modifiche possono essere controllate nel branch 'correzioni-finale'
