### ISSUE TITLE
Uso di enumerazioni

### ISSUE THREAD

**Issue by supix** [salvatoredacri/Battaglia-Navale#15]
https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/giocatore.py#L155

Lo stato di una cella del campo di battaglia può assumere uno tra N valori. E' stato scelto di rappresentarlo con degli interi.
Un'altra possibilità sarebbe potuta essere quella di utilizzare delle enumerazioni, come indicato [a questo link](https://docs.python.org/3/library/enum.html).

I vantaggi nell'uso di un'enum sono i seguenti:

* correttezza: non è possibile rappresentare un valore inesistente;
* leggibilità: il valore di un'enum ha un significato di immediata comprensione.

**Comment by Frise99** [comment]
È stata implementata la soluzione suggerita che utilizza un'enumerazione per rappresentare lo stato delle celle nel campo di battaglia. Utilizzando l'enumerazione StatoCella, i membri come VUOTA, COLPITA, ACQUA e NAVE rappresentano chiaramente gli stati delle celle, rendendo il codice più comprensibile e manutenibile nel tempo.

Tutte le modifiche possono essere controllate nel branch 'Correzioni 2.0'

**Comment by supix** [comment]
La stessa tecnica di uso delle enumerazioni può essere utilizzata per l'orientamento della nave.

Un sintomo lampante di questa necessità è rappresentato dalla numerosità nel vostro codice del seguente controllo:

```
if orientamento == "orizzontale" or orientamento == "o"
```

Altri sintomi sono nelle risposte alle seguenti domande:

> _Come dovrei modificare il mio codice se mi chiedessero di cambiare la lingua dell'interfaccia?_
> _Quanto è facile commettere un errore di ortografia nello scrivere questa condizione (per es. 'orizontale' invece di 'orizzontale')?_
> _E quanto è facile in seguito rilevare un errore del genere?_

Potrebbe essere meglio leggere l'input dalla GUI e trasformarlo subito in un'enumerazione (che è un valore _blindato_) che verrà usata in tutto il resto del programma, avendo una chiara e stabile semantica.

**Comment by Frise99** [comment]
E' stata utilizzata la tecnica di uso delle enumerazioni anche per la gestione dell'orientamento della nave.

Tutte le modifiche possono essere controllate nel branch `correzioni-finale`

**Comment by supix** [comment]
Alcuni suggerimenti.

La variabile chiamata `esito_colpo` ha l'aria di essere un'enumerazione (per es. colpo riuscito/fallito). Invece analizzando meglio il codice ci si accorge che è in realtà un booleano. Per rendere più chiara questa (giusta) scelta sarebbe meglio chiamarla `colpo_riuscito` (che vale `True` oppure  `False`).

https://github.com/salvatoredacri/Battaglia-Navale/blob/022ecc86e0cfd6a60160eb5414cdd6f57f4af807/strategy.py#L5

In questo modo anche il controllo `if colpo_riuscito`... è più chiaro.

Questo ramo `else` è identico al ramo `if`:

https://github.com/salvatoredacri/Battaglia-Navale/blob/022ecc86e0cfd6a60160eb5414cdd6f57f4af807/strategy.py#L25

In questo punto:

https://github.com/salvatoredacri/Battaglia-Navale/blob/022ecc86e0cfd6a60160eb5414cdd6f57f4af807/strategy.py#L79

se la modalità fosse diversa sia da 0 che da 1, il metodo non restituirebbe nulla. Meglio inserire un altro ramo in cui si solleva un'eccezione.

Perché dare la responsabilità alla classe `CambioTurnoStrategy` di verificare sia il prossimo giocatore che l'eventuale terminazione della partita? Sono due responsabilità diverse e andrebbero assegnate a due classi diverse (vedi [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle) in [SOLID](https://en.wikipedia.org/wiki/SOLID)).

**Comment by Frise99** [comment]
E' stata rinominata la variabile `esito_colpo` in `colpo_riuscito`:
https://github.com/salvatoredacri/Battaglia-Navale/blob/eae51c96cd4a0be797241366713e3065cdf3d119/strategy.py#L5
E' stato aggiunto il ramo in cui viene sollevata l'eccezione per gestire il caso in cui sia diversa da 0 e 1:
https://github.com/salvatoredacri/Battaglia-Navale/blob/29aabea0dd36d7deabdd4fffd11764fd6465dc6c/strategy.py#L58
Inoltre sono state apportate alcune modifiche affinché venga garantito il principio di singola responsabilità.

Tutte le modifiche possono essere controllate nel branch 'correzioni-finale'

**Comment by supix** [comment]
Ok per le modifiche apportate.

Per quanto riguarda l'enumerazione utilizzata per l'orientamento ho appena proposto una modifica mediante [una pull-request](https://github.com/salvatoredacri/Battaglia-Navale/pull/20).

Verificate se vi convince e, nel caso, la approvate.

**Comment by salvatoredacri** [comment]
Abbiamo preso in considerazione la pull-request ed è stato effettuato il merge.
