### ISSUE TITLE
Strategia di gestione del turno di gioco

### ISSUE THREAD

**Issue by supix** [salvatoredacri/Battaglia-Navale#16]
La logica della doppia modalità di alternanza turno è spalmata in molti punti del programma:

https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/main.py#L70

https://github.com/salvatoredacri/Battaglia-Navale/blob/79ace74e7dedff3004ed9385cc717b538d1b8e83/giocatore.py#L129

https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/giocatore.py#L176

https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/giocatore.py#L182

https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/giocatore.py#L191

https://github.com/salvatoredacri/Battaglia-Navale/blob/2f516cad07cc91593b0dca46cae139cb994e2075/giocatore.py#L198

Una soluzione più elegante consiste nell'inserire un unico while nel main() (detto _main loop_) con una chiamata al gioco del "giusto" giocatore, lasciando che una specifica classe, di volta in volta, decida di chi è il turno: questa classe prende in ingresso il giocatore corrente, l'esito del suo tiro e la strategia di gioco scelta (se il giocatore il cui colpo va a segno ha diritto a tirare nuovamente, o meno) e restituisce il giocatore a cui tocca il successivo turno. A seconda della strategia di gioco si istanzia la giusta classe (quindi si usa proprio il pattern strategy). Il risultato in pseudo-codice è il seguente.

```
cambio_turno_strategy = get_cambio_turno_strategy(modalità) //qui si usa il pattern strategy
giocatore_di_turno = giocatore1
while partita_non_finita():
  esito = giocatore_di_turno.gioca()
  giocatore_di_turno = cambio_turno_strategy.get_prossimo_giocatore(giocatore_di_turno, esito)
```

In questo modo si eliminano un po' di `if` e un'eventuale aggiunta/modifica della modalità di alternanza è ben isolata in uno specifico punto del programma.

**Comment by Frise99** [comment]
È stato creato un nuovo branch chiamato `correzioni-finale` in cui sono presenti tutte le modifiche apportate al programma.

A partire dal suo pseudo-codice, abbiamo sviluppato una nuova soluzione per gestire l'alternanza dei turni in base alle modalità di gioco. Questa soluzione utilizza la tecnica del pattern strategy.
Il metodo implementato si trova nel modulo `strategy`.

**Comment by iannellog** [comment]
Il programma così ristrutturato non funziona.
I colpi di un giocatore vengono applicati al **suo** campo di gioco e non a quello dell'avversario.
In generale mi sembra che avete applicato male le modifiche suggerite dal prof. Esposito, ma lascio a lui una valutazione. 
Come suggerimenti generali:
- avete fatto bene ad aprire un branch dal momento che la ristrutturazione del codice era significativa, ma prima di rispondere a una issue effettuare del testing per non esporre codice non verificato; 
- in questo caso poiché il codice è stato profondamente ristrutturato andava investito del tempo per verificare che le funzionalità fossero implementate correttamente;
- dopo aver effettuato il testing e verificato che la soluzione è corretta fate il merge con il branch di partenza per evitare di avere versioni incompatibili e non evidenziare chiaramente qiuale è quella stabile

**Comment by Frise99** [comment]
E' stato corretto il problema, ora i colpi vengono applicati al campo di gioco dell'avversario.
Attendiamo conferme che tutto sia corretto per effettuare un eventuale merge con il main branch.

Tutte le modifiche possono essere controllate nel branch 'correzioni-finale'

**Comment by supix** [comment]
Il problema indicato dal Prof. Iannello sembra risolto.

Questa correzione doveva essere realizzata in un *unico* commit.

Facendo un commit per ogni file avete ottenuto dei punti di commit in cui i files non sono coerenti. Per es. nel commit al file giocatore.py (3974430) il metodo `turno(self, avversario)` è incoerente con la chiamata al metodo `turno()` eseguita nel main e corretta al successivo commit (f5c8c48).

Inoltre ogni commit va commentato con messaggi molto chiari su ciò che si è fatto, per far comprendere a chi legge (che potete essere anche voi stessi qualche tempo dopo) cosa cambia da una versione all'altra. Si veda [qui](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) e [qui](https://opensource.com/article/22/12/git-commit-message).
