### ISSUE TITLE
Classe Navi e commento generale

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#2]
Costruttore:
- a che serve il parametro *quantita*? nei commenti non se ne parla
- il commento *Lista delle posizioni occupate dalla nave* a che si riferisce? all'attributo *coordinate*?
- bisognerebbe chiarire nei commenti il tipo dell'attributo *coordinate*: è una lista, una tupla? che tipo di informazioni contiene?
- perché solo le coordinate? non conviene memorizzare anche l'orientamento che insieme alle coordiante della prima casella definirirebbe completamente la posizine della nave? (vedi commento su *controlla_colpo*)

controlla_colpo:
- per come è scritto il codice l'attributo *coordinate* potrebbe essere una lista vuota, in tal caso la condizione alla riga 47 è sempre falsa (ho visto che in realtà a un certo punto gli viene assegnata una lista, ma questo crea un un intreccio con il codice di *posiziona_navi* nel file *griglia.py* che viola il principio di incapsulamento delle informazioni all'interno di una classe)
- perché bisogna passargli una griglia? la lista in *coordinate* sarebbe sufficiente (se poi fosse disponibile l'orientamento e la posizione della prima casella della nave non ci sarebbe bisogno neppure di una lista)
- il metodo viene chiamato almeno due volte nello stesso turno (in *turno* e nel metodo *colpita*) 

colpita:
- non si può fondere con il metodo precedente? perché servono due metodi distinti?

In generale mi sembra che tutto il programma vada ristrutturato per fare in modo che le varie funzioni siamo meglio distribuite tra le classi senza sovrapposizioni e rinvii da un pezzo di codice all'altro.

**Comment by Frise99** [comment]
Sono stati aggiunti i commenti mancanti e rimossi quelli superflui per rendere il codice più comprensibile. In particolare, abbiamo apportato le seguenti modifiche:

- Nel costruttore della classe Navi, abbiamo deciso di non includere i parametri 'orientamento' e 'coordinate_iniziali', poiché non sembrano influire sulla nostra logica della classe e del gioco. Pertanto, non li abbiamo utilizzati per evitare confusione.

- All'interno della classe Navi, abbiamo aggiunto una funzione chiamata 'set_coordinate' per preservare il principio di incapsulamento. Questa funzione consente di impostare le coordinate della nave con un valore specifico, garantendo che l'accesso diretto alle coordinate sia limitato.

- Abbiamo modificato le funzioni 'controlla_colpo' e 'colpita' per includere solo gli argomenti necessari. Abbiamo deciso di separarle per migliorare la leggibilità e la modularità del codice, in modo che ogni funzione abbia una responsabilità specifica.

- Infine, nel modulo gioco.py, abbiamo rimosso una chiamata superflua alla funzione 'controlla_colpo' che sembrava non essere necessaria per la logica del gioco.

Tutte le modifiche possono essere controllate nel branch _correzioni_

**Comment by iannellog** [comment]
L'attributo `quantita` va eliminato.
Poiché un oggetto `Navi` rappresenta UNA SOLA nave l'attributo `quantita` non ha senso.
Tra l'altro l'attributo non viene usato mai nei metodi della classe, il che conferma che non serve. 

Un altro problema è che l'attributo `coordinate` è inizialmente una lista vuota ed è richiesta l'esecuzione del metodo `set_coordinate` prima di poter chiamare gli altri metodi della classe. In altre parole, una volta creato un oggetto `Navi` non posso chiamare il metodo `contrlla_colpo` se non ho prima chiamato il metodo `set_coordinate` (se lo si fa si ottiene sempre False). 

Questo non va bene. Bisogna spostare (ed eventualmente adattare) una parte del codice della funzione `posiziona_navi` dentro il costruttore di `Navi` in modo che quando viene crearto l'oggetto venga inizializzato correttamente anche l'attributo `coordinate` (ovviamente bisogna passare al costruttore la posizione e l'orientamento). In alternativa si può costruire la lista di coordinate prima di creare l'oggetto e passare al costruttore la lista.

**Comment by Frise99** [comment]
L'attributo "quantita" è stato rimosso poiché è risultato essere inutile nel contesto della classe "Navi". Considerando che un oggetto "Navi" rappresenta una singola nave, l'attributo "quantita" non aveva senso e non veniva utilizzato in nessuno dei metodi della classe. La sua rimozione ha permesso di semplificare il codice e rendere la classe più coerente con il suo scopo specifico.

Inoltre, la funzione "posiziona_navi" è stata modificata per creare un oggetto della classe "Navi" correttamente inizializzato. Ora, invece di creare solo una lista di coordinate, la funzione crea un oggetto "Navi" passando gli argomenti "orientamento", "riga_iniz" e "colonna_iniz" al costruttore della classe. Questo assicura che l'oggetto "Navi" sia correttamente inizializzato con le informazioni necessarie per rappresentare una nave e le sue posizioni.

Inoltre, l'oggetto "Navi" appena creato viene inserito all'interno di una lista che contiene tutti gli oggetti "Navi" posizionati dagli utenti per il giocatore corrispondente. Questo consente di tenere traccia delle navi posizionate da ciascun giocatore in modo organizzato e accessibile.

Complessivamente, queste modifiche hanno reso il codice più chiaro, efficiente e coerente con l'obiettivo di rappresentare le navi all'interno del gioco.

**Comment by iannellog** [comment]
Chiudo questa issue, ma il problema non è completamente risolto. Si vedano i commenti sulla struttura della soluzione.
