### ISSUE TITLE
funzione *posiziona_navi*

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#3]
Nella funzione si solleva un eccezione che viene catturata nella stessa funzione.
In una caso come questo bastava stampare il messaggio di warning e usare l'istruzione *continue*.
L'eccezione si solleva quandoo deve essere catturata all'esterno.

**Comment by Frise99** [comment]
La funzione posiziona_navi è stata aggiornata per gestire correttamente l'eccezione che può essere sollevata all'interno di una funzione esterna. Questa modifica garantisce che l'eccezione venga catturata e gestita correttamente, evitando che il programma si interrompa in modo anomalo. Ora, se viene sollevata un'eccezione all'interno della funzione esterna, posiziona_navi sarà in grado di gestirla in modo adeguato, consentendo al programma di proseguire con il normale flusso di esecuzione.

Tutte le modifiche possono essere controllate nel branch _correzioni_

**Comment by iannellog** [comment]
Ora va meglio, ma non capisco però perché avete gestito con logica diversa gli errori sulle coordinate e sull'orientamento (in un caso usando `continue`, nell'altro sollevando un'eccezione dentro una doppia chiamata annidata.
Si tratta di una scelta apparentemente non motivata e inutilmente complicata.

**Comment by salvatoredacri** [comment]
La funzione `posiziona_navi` è stata aggiornata per utilizzare l'istruzione `continue` al fine di segnalare gli errori durante l'inserimento delle coordinate e/o dell'orientamento delle navi. Inoltre, la informiamo che stiamo attualmente lavorando sulla "Issue n2".``

Tutte le modifiche possono essere controllate nel branch correzioni
