### ISSUE TITLE
Commenti

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#4]
Dovere essere uniformi nell'iuso dei commenti: ci sono file discretamente commentati e altri in cui i commenti mancano completamente o quasi. Fate in modo che tutte le funzioni e tutti i metodi siano commentati in modo completo e uniforme.

**Comment by Frise99** [comment]
Sono stati aggiunti i commenti mancanti ai file del progetto, migliorando così la chiarezza e la comprensione del codice. Ogni file dovrebbe ora essere descritto in modo chiaro, fornendo informazioni rilevanti sulle funzioni, le classi e le variabili utilizzate.

Tutte le modifiche possono essere controllate nel branch _correzioni_

**Comment by iannellog** [comment]
Quà e là c'è ancora qualche commento migliorabile, ma sostanzialmente c'è un miglioramento.
