### ISSUE TITLE
File griglia.py

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#5]
Non varrebbe la pena creare una classe *Griglia*?
Aiuterebbe a strutturare meglio il programma.

Funzione *stampa_griglia*
- mancano i commenti
- il parametro *dimensione* è inutile (la dimensione dell'oggetto *griglia* si può ricavare direttamente)

**Comment by Frise99** [comment]
La funzione stampa_griglia è stata modificata con il solo argomento necessario (_griglia_) ed è stata commentata.

Per quanto riguarda la scelta di non utilizzare una classe separata per la gestione della griglia nel progetto è stata motivata dalla relativa semplicità delle operazioni coinvolte. La griglia di gioco è stata rappresentata efficacemente utilizzando una lista bidimensionale, consentendo un accesso e una modifica diretti dei valori.  Poiché il progetto non richiedeva funzionalità complesse o specifiche per la gestione della griglia, l'adozione di una classe dedicata avrebbe introdotto un overhead di codice aggiuntivo e una maggiore complessità. La scelta di mantenere il codice semplice e leggibile è stata preferita, focalizzando gli sforzi su altre parti del progetto che richiedevano maggiore attenzione e sviluppo

Tutte le modifiche possono essere controllate nel branch _correzioni_

**Comment by iannellog** [comment]
La valutazione che fate non è corretta.

Il codice sarebbe stato più semplice da leggere introducedo la classe Griglia infatti c'è un intreccio con la classe Navi (vedi altra issue). Una buona soluzione (non l'unica) avrebbe potuto essere:
- una classe `Griglia` che contiene un riferimento a una lista di oggetti `Navi` e gestisce la rappresentazione matriciale del campo di gioco mantendola coerente con gli oggetti `Navi`della lista
- la classe `Griglia`, tra gli altri, ha un metodo `verifica_colpo` che:
   - verifica se ha colpito una nave scorrendo la lista di navi
   - in base al risultato modifica la rappresentazione matriciale
   - restituisce il risultato: 
      - colpo a vuoto
      - colpita
      - affondata
      - vittoria

Per ora chiudo la issue, ma riflettete se non converrebbe rivedere alcune scelte di progetto.
