### ISSUE TITLE
Comando `cls`

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#6]
I Mac e Linux non hanno il comando `cls`: al suo posto hanno `clear`.
Può essere usata la funzione *system* del modulo *platform*:
> Help on function system in module platform:
>
> **system()**
>      Returns the system/OS name, e.g. 'Linux', 'Windows' or 'Java'.
>     An empty string is returned if the value cannot be determined.

per eseguire il comando giusto.

**Comment by Frise99** [comment]
È stata creata la funzione _clear_console() appositamente per gestire la pulizia della console durante l'esecuzione del gioco, tenendo conto della possibilità che il codice venga utilizzato su diversi sistemi operativi. Grazie a questa funzione, la pulizia del terminale o della console di output avverrà con successo, indipendentemente dal sistema operativo in uso. La funzione sfrutta il modulo os per determinare il sistema operativo corrente e selezionare il comando appropriato per la pulizia. In questo modo, si garantisce un comportamento uniforme e corretto del codice, senza dover preoccuparsi delle differenze tra i vari sistemi operativi.

Tutte le modifiche possono essere controllate nel branch _correzioni_

**Comment by iannellog** [comment]
Se volete essere *perfetti* invece di os.name, usate sys.platform (https://docs.python.org/3/library/sys.html) oppure platform.system() (https://docs.python.org/3/library/platform.html), inciando il comando corretto per i sistemi windows e unix-like e sollevando un'eccezione in tutti gli altri casi (l'eccezione va poi catturata nel programma principale facendo terminare il programma con un messaggio tipo "piattaforma non supportata").
