### ISSUE TITLE
Struttura complessiva della soluzione e commenti al main

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#7]
La soluzione non è ben strutturata con un uso molto limitato delle classi (solo la classe Navi).

Di seguito alcuni commenti che però richiederebbero una revisione sostanziale del coodice che appare già in uno stadio finale di sviluppo.

- Si è rinunciato a introdurre una classe `Griglia` e il codice che manipola il campo di gioco è sparso in varie parte del codice.
Anche l'uso della classe `Navi` è poco ortodosso:
   - si crea una prima lista di oggetti `Navi` in `standards.crea_lista_navi` (peraltro solo parzialmente inizializzati perché manca completamente la posizione)
   - si crea poi una differente lista di oggetti `Navi` in `griglia.posiziona_navi` (e l'altra lista non viene più usata) questa cvolta completamente inizializzati

- Nel programma principale invece di chiamare la funzione `turno` cambiando i parametri effettivi a seconda del giocatore si assegnano i parametri del giocatore a delle variabili di appoggio per poi chiamare la funzione con parametri effettivi fissi: in genere non si usano così i sottoprogrammi.

- Tra l'altro se si fosse introdotta una classe `Giocatore` che riferiva tutti gli oggetti del giocatore (griglia dell'avversatrio, lista delle proprie navi) la funzione `turno` avrebbe avuto bisogno di meno parametri.

- La funzione `turno` restituisce l'oggetto `griglia_colpi` che però non viene poi usato (in realtà il programma funziona lo stesso perché l'oggetto viene modificato all'interno dalla funzione come effetto collaterale).

**Comment by Frise99** [comment]
E' stata considerata l'idea di modificare la struttura del programma aggiungendo una classe 'giocatore'. Questa nuova classe ha introdotto una maggiore modularità e organizzazione al codice, fornendo una rappresentazione specifica del giocatore nel contesto del gioco della battaglia navale.

Prima dell'introduzione della classe 'giocatore' le funzionalità legate al giocatore erano  distribuite in vari moduli o frammenti di codice. Queste funzioni sono state poi riorganizzate e adattate per essere incorporate all'interno della classe 'giocatore', offrendo una soluzione più strutturata e coerente.

La classe 'giocatore' è stata progettata per incapsulare le informazioni e le azioni specifiche del giocatore. Ogni istanza della classe rappresenta un giocatore separato, con il proprio **nome, griglia di gioco, griglia dei colpi effettuati, navi posizionate e modalità di gioco**. Questo consente di gestire facilmente più giocatori e tener traccia delle loro interazioni nel contesto della partita.

Le funzioni che erano state precedentemente implementate in altri moduli sono state adattate per diventare metodi della classe 'giocatore'. Ad esempio, la funzione di posizionamento delle navi è stata trasformata nel metodo 'posiziona_navi', che ora fa parte della classe 'giocatore'. Allo stesso modo, il metodo 'turno' gestisce le azioni e le decisioni del giocatore durante il proprio turno di gioco.

Questa nuova struttura ha portato ad un aggiornamento anche del programma principale. Ora, invece di avere una serie di funzioni e chiamate di funzioni sparse nel codice principale, si utilizza la classe 'giocatore' per gestire tutte le operazioni correlate al giocatore. Ciò rende il codice più leggibile, manutenibile e facilita l'aggiunta di nuove funzionalità nel contesto del giocatore.

In generale, l'introduzione della classe 'giocatore' ha migliorato l'organizzazione del codice e la rappresentazione del giocatore nel gioco della battaglia navale. Ha consentito di incapsulare le informazioni e le azioni del giocatore in un'unica entità coerente, semplificando così la gestione e l'interazione con il giocatore nel contesto della partita.

Tutte le modifiche e aggiornamenti possono essere controllate nel nuovo branch 'correzioni 2.0'
