### ISSUE TITLE
Commenti di dettaglio al main

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#8]
Alla riga 28 si chiama la funzione `check_parser` dopo che la variabile àrgs` è stata abbondantemente usata: la cosa non sembra avere molto senso

**Comment by Frise99** [comment]
La chiamata alla funzione 'check_parser' è stata spostata alla riga 18. 
Inoltre, tutte le modifiche sono state apportate nel nuovo branch chiamato "correzioni-2.0" per affrontare le modifiche strutturali necessarie a seguito dell'issue 7.
