### ISSUE TITLE
Commenti di dettaglio a standards.py

### ISSUE THREAD

**Issue by iannellog** [salvatoredacri/Battaglia-Navale#9]
- quale è la logica della funzione `crea_lista_navi`? 
- perché decremente la variabile `num_navi`che non mi pare venga usata? 
- perché fa una copia di `args`?

**Comment by Frise99** [comment]
La funzione crea_lista_navi  prende due argomenti: args (gli argomenti della riga di comando) e navi_disponibili (le navi disponibili).

Viene inizializzata una lista vuota chiamata lista_navi che conterrà le navi selezionate.

Viene iterato attraverso ogni nave disponibile in navi_disponibili.values().

Per ogni nave, viene ottenuto il valore dell'attributo corrispondente al suo nome utilizzando la funzione getattr(args, nave.nome).

Se il numero di navi (num_navi) è maggiore di 0, significa che sono state specificate navi di quel tipo come argomenti della riga di comando.

Viene quindi eseguito un loop per creare num_navi istanze di quella nave.

Per ogni nave, viene creata una nuova istanza chiamata nuova_nave utilizzando il costruttore della classe Navi. I parametri passati sono il nome della nave, la sua lunghezza e gli altri parametri vengono inizializzati a None.

La nuova nave viene quindi aggiunta alla lista delle navi lista_navi utilizzando il metodo append.

Dopo aver iterato su tutte le navi disponibili, la funzione restituisce la lista delle navi selezionate.

In sintesi, la funzione prende in input gli argomenti della riga di comando e le navi disponibili, e restituisce una lista di istanze di navi basata sui valori specificati come argomenti.

Sono state eliminate la variabile 'num_navi' e al copia di args in quanto non risultavano influenti.

Tutte le modifiche possono essere  controllate nel nuovo branch 'correzioni 2.0'
